- name: Configure-firewall
  become: true
  hosts: all
  tasks:
    - name: Backup and "flush" iptables rules files
      ansible.builtin.shell: |
        mv -nv /etc/iptables/rules.v{4,6} /root/
        touch /etc/iptables/rules.v{4,6}
        chmod 644 /etc/iptables/rules.v{4,6}
      register: result
      args:
        executable: /bin/bash
      tags:
        - firewall
        - backup
      changed_when:
        - result.rc == 0
