- name: docker-install
  become: true
  hosts: all
  tasks:
    # Check for unattended-upgrades and kill it
    - name: Killing unattended-upgrades if any
      shell: pkill -f unattended -e
      ignore_errors: true

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: latest
        update_cache: true
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
    - name: install 'Docker SDK for Python'
      pip:
        name: docker
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release | lower }} stable
        state: present
  
    - name: Update apt and install docker-ce
      ansible.builtin.apt:
        pkg: 
          - docker-ce
        state: latest
        update_cache: true
      register: apt_action
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)

    - name: Install docker-compose  
      get_url: 
        url : https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
