# initial configuration
- name: Init
  become: true
  hosts: all
  tasks:
    - name: Set up authorized keys for root
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', item) }}"
      with_fileglob:
        - files/admin_pubkeys/*.pub
    - name: Disable password login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: ^PasswordAuthentication
        line: PasswordAuthentication no
        state: present
    # Check for unattended-upgrades and kill it
    - name: Killing unattended-upgrades if present
      ansible.builtin.command: pkill -f unattended -e
      register: result
      changed_when:
        - result == 0
      ignore_errors: true
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true
    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
        force: true
    - name: Autoremove dependencies
      ansible.builtin.apt:
        autoremove: true

- name: Install docker stuff
  import_playbook: docker-install.yml

- name: Configure iptables firewall
  import_playbook: configure-firewall.yml

  # reboot
- name: Reboot after install is done
  become: true
  hosts: all
  tasks:
    - name: Rebooting Machine...
      ansible.builtin.reboot:

- name: Install and run bridge container
  ansible.builtin.import_playbook: run_bridge.yml
